/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.ui.contentassist;

import org.xtext.ecse439.project.ui.contentassist.AbstractAirportProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AirportProposalProvider extends AbstractAirportProposalProvider {
}
