/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project;

import org.xtext.ecse439.project.AbstractAirportRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AirportRuntimeModule extends AbstractAirportRuntimeModule {
}
