/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project;

import org.xtext.ecse439.project.AirportStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AirportStandaloneSetup extends AirportStandaloneSetupGenerated {
  public static void doSetup() {
    AirportStandaloneSetup _airportStandaloneSetup = new AirportStandaloneSetup();
    _airportStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
