/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.ecse439.project.airport.AirportPackage
 * @generated
 */
public interface AirportFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AirportFactory eINSTANCE = org.xtext.ecse439.project.airport.impl.AirportFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Domainmodel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domainmodel</em>'.
   * @generated
   */
  Domainmodel createDomainmodel();

  /**
   * Returns a new object of class '<em>Airport</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Airport</em>'.
   * @generated
   */
  Airport createAirport();

  /**
   * Returns a new object of class '<em>All Terminals</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Terminals</em>'.
   * @generated
   */
  AllTerminals createAllTerminals();

  /**
   * Returns a new object of class '<em>All Runways</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Runways</em>'.
   * @generated
   */
  AllRunways createAllRunways();

  /**
   * Returns a new object of class '<em>All Gates</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Gates</em>'.
   * @generated
   */
  AllGates createAllGates();

  /**
   * Returns a new object of class '<em>All Airlines</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Airlines</em>'.
   * @generated
   */
  AllAirlines createAllAirlines();

  /**
   * Returns a new object of class '<em>All Flights</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>All Flights</em>'.
   * @generated
   */
  AllFlights createAllFlights();

  /**
   * Returns a new object of class '<em>Schedule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Schedule</em>'.
   * @generated
   */
  Schedule createSchedule();

  /**
   * Returns a new object of class '<em>Flight</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flight</em>'.
   * @generated
   */
  Flight createFlight();

  /**
   * Returns a new object of class '<em>Fl Gate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fl Gate</em>'.
   * @generated
   */
  FlGate createFlGate();

  /**
   * Returns a new object of class '<em>Terminal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminal</em>'.
   * @generated
   */
  Terminal createTerminal();

  /**
   * Returns a new object of class '<em>Runway</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Runway</em>'.
   * @generated
   */
  Runway createRunway();

  /**
   * Returns a new object of class '<em>Gate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gate</em>'.
   * @generated
   */
  Gate createGate();

  /**
   * Returns a new object of class '<em>Airline</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Airline</em>'.
   * @generated
   */
  Airline createAirline();

  /**
   * Returns a new object of class '<em>Date</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Date</em>'.
   * @generated
   */
  Date createDate();

  /**
   * Returns a new object of class '<em>Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time</em>'.
   * @generated
   */
  Time createTime();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AirportPackage getAirportPackage();

} //AirportFactory
