/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.ecse439.project.airport.AirportFactory
 * @model kind="package"
 * @generated
 */
public interface AirportPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "airport";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/ecse439/project/Airport";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "airport";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AirportPackage eINSTANCE = org.xtext.ecse439.project.airport.impl.AirportPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.DomainmodelImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getDomainmodel()
   * @generated
   */
  int DOMAINMODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Domainmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.AirportImpl <em>Airport</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.AirportImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAirport()
   * @generated
   */
  int AIRPORT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Schedule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__SCHEDULE = 1;

  /**
   * The feature id for the '<em><b>All Run</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__ALL_RUN = 2;

  /**
   * The feature id for the '<em><b>All Gat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__ALL_GAT = 3;

  /**
   * The feature id for the '<em><b>All Air</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__ALL_AIR = 4;

  /**
   * The feature id for the '<em><b>All Fli</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__ALL_FLI = 5;

  /**
   * The feature id for the '<em><b>All Ter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT__ALL_TER = 6;

  /**
   * The number of structural features of the '<em>Airport</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRPORT_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.AllTerminalsImpl <em>All Terminals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.AllTerminalsImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllTerminals()
   * @generated
   */
  int ALL_TERMINALS = 2;

  /**
   * The feature id for the '<em><b>Terminals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_TERMINALS__TERMINALS = 0;

  /**
   * The number of structural features of the '<em>All Terminals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_TERMINALS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.AllRunwaysImpl <em>All Runways</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.AllRunwaysImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllRunways()
   * @generated
   */
  int ALL_RUNWAYS = 3;

  /**
   * The feature id for the '<em><b>Runways</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_RUNWAYS__RUNWAYS = 0;

  /**
   * The number of structural features of the '<em>All Runways</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_RUNWAYS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.AllGatesImpl <em>All Gates</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.AllGatesImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllGates()
   * @generated
   */
  int ALL_GATES = 4;

  /**
   * The feature id for the '<em><b>Gates</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_GATES__GATES = 0;

  /**
   * The number of structural features of the '<em>All Gates</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_GATES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.AllAirlinesImpl <em>All Airlines</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.AllAirlinesImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllAirlines()
   * @generated
   */
  int ALL_AIRLINES = 5;

  /**
   * The feature id for the '<em><b>Airline</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_AIRLINES__AIRLINE = 0;

  /**
   * The number of structural features of the '<em>All Airlines</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_AIRLINES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.AllFlightsImpl <em>All Flights</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.AllFlightsImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllFlights()
   * @generated
   */
  int ALL_FLIGHTS = 6;

  /**
   * The feature id for the '<em><b>Flights</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_FLIGHTS__FLIGHTS = 0;

  /**
   * The number of structural features of the '<em>All Flights</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALL_FLIGHTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.ScheduleImpl <em>Schedule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.ScheduleImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getSchedule()
   * @generated
   */
  int SCHEDULE = 7;

  /**
   * The feature id for the '<em><b>Date</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__DATE = 0;

  /**
   * The feature id for the '<em><b>Fl Gate</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE__FL_GATE = 1;

  /**
   * The number of structural features of the '<em>Schedule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.FlightImpl <em>Flight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.FlightImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getFlight()
   * @generated
   */
  int FLIGHT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__NAME = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__TIME = 1;

  /**
   * The feature id for the '<em><b>Airplane Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__AIRPLANE_SIZE = 2;

  /**
   * The feature id for the '<em><b>Req Runway Lg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT__REQ_RUNWAY_LG = 3;

  /**
   * The number of structural features of the '<em>Flight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIGHT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.FlGateImpl <em>Fl Gate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.FlGateImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getFlGate()
   * @generated
   */
  int FL_GATE = 9;

  /**
   * The feature id for the '<em><b>Flight</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FL_GATE__FLIGHT = 0;

  /**
   * The feature id for the '<em><b>Gate</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FL_GATE__GATE = 1;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FL_GATE__TIME = 2;

  /**
   * The number of structural features of the '<em>Fl Gate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FL_GATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.TerminalImpl <em>Terminal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.TerminalImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getTerminal()
   * @generated
   */
  int TERMINAL = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Runway</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINAL__RUNWAY = 1;

  /**
   * The feature id for the '<em><b>Gates</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINAL__GATES = 2;

  /**
   * The feature id for the '<em><b>Airline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINAL__AIRLINE = 3;

  /**
   * The number of structural features of the '<em>Terminal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINAL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.RunwayImpl <em>Runway</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.RunwayImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getRunway()
   * @generated
   */
  int RUNWAY = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUNWAY__NAME = 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUNWAY__LENGTH = 1;

  /**
   * The feature id for the '<em><b>Used</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUNWAY__USED = 2;

  /**
   * The number of structural features of the '<em>Runway</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RUNWAY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.GateImpl <em>Gate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.GateImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getGate()
   * @generated
   */
  int GATE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Max Ap Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE__MAX_AP_SIZE = 1;

  /**
   * The number of structural features of the '<em>Gate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.AirlineImpl <em>Airline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.AirlineImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAirline()
   * @generated
   */
  int AIRLINE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRLINE__NAME = 0;

  /**
   * The number of structural features of the '<em>Airline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AIRLINE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.DateImpl <em>Date</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.DateImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getDate()
   * @generated
   */
  int DATE = 14;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__DAY = 0;

  /**
   * The feature id for the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__MONTH = 1;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE__YEAR = 2;

  /**
   * The number of structural features of the '<em>Date</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.ecse439.project.airport.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ecse439.project.airport.impl.TimeImpl
   * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getTime()
   * @generated
   */
  int TIME = 15;

  /**
   * The feature id for the '<em><b>Hour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__HOUR = 0;

  /**
   * The feature id for the '<em><b>Minute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__MINUTE = 1;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Domainmodel <em>Domainmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domainmodel</em>'.
   * @see org.xtext.ecse439.project.airport.Domainmodel
   * @generated
   */
  EClass getDomainmodel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ecse439.project.airport.Domainmodel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.ecse439.project.airport.Domainmodel#getElements()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Airport <em>Airport</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Airport</em>'.
   * @see org.xtext.ecse439.project.airport.Airport
   * @generated
   */
  EClass getAirport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Airport#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ecse439.project.airport.Airport#getName()
   * @see #getAirport()
   * @generated
   */
  EAttribute getAirport_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.Airport#getSchedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Schedule</em>'.
   * @see org.xtext.ecse439.project.airport.Airport#getSchedule()
   * @see #getAirport()
   * @generated
   */
  EReference getAirport_Schedule();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.Airport#getAllRun <em>All Run</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>All Run</em>'.
   * @see org.xtext.ecse439.project.airport.Airport#getAllRun()
   * @see #getAirport()
   * @generated
   */
  EReference getAirport_AllRun();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.Airport#getAllGat <em>All Gat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>All Gat</em>'.
   * @see org.xtext.ecse439.project.airport.Airport#getAllGat()
   * @see #getAirport()
   * @generated
   */
  EReference getAirport_AllGat();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.Airport#getAllAir <em>All Air</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>All Air</em>'.
   * @see org.xtext.ecse439.project.airport.Airport#getAllAir()
   * @see #getAirport()
   * @generated
   */
  EReference getAirport_AllAir();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.Airport#getAllFli <em>All Fli</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>All Fli</em>'.
   * @see org.xtext.ecse439.project.airport.Airport#getAllFli()
   * @see #getAirport()
   * @generated
   */
  EReference getAirport_AllFli();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.Airport#getAllTer <em>All Ter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>All Ter</em>'.
   * @see org.xtext.ecse439.project.airport.Airport#getAllTer()
   * @see #getAirport()
   * @generated
   */
  EReference getAirport_AllTer();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.AllTerminals <em>All Terminals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Terminals</em>'.
   * @see org.xtext.ecse439.project.airport.AllTerminals
   * @generated
   */
  EClass getAllTerminals();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ecse439.project.airport.AllTerminals#getTerminals <em>Terminals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Terminals</em>'.
   * @see org.xtext.ecse439.project.airport.AllTerminals#getTerminals()
   * @see #getAllTerminals()
   * @generated
   */
  EReference getAllTerminals_Terminals();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.AllRunways <em>All Runways</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Runways</em>'.
   * @see org.xtext.ecse439.project.airport.AllRunways
   * @generated
   */
  EClass getAllRunways();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ecse439.project.airport.AllRunways#getRunways <em>Runways</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Runways</em>'.
   * @see org.xtext.ecse439.project.airport.AllRunways#getRunways()
   * @see #getAllRunways()
   * @generated
   */
  EReference getAllRunways_Runways();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.AllGates <em>All Gates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Gates</em>'.
   * @see org.xtext.ecse439.project.airport.AllGates
   * @generated
   */
  EClass getAllGates();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ecse439.project.airport.AllGates#getGates <em>Gates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Gates</em>'.
   * @see org.xtext.ecse439.project.airport.AllGates#getGates()
   * @see #getAllGates()
   * @generated
   */
  EReference getAllGates_Gates();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.AllAirlines <em>All Airlines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Airlines</em>'.
   * @see org.xtext.ecse439.project.airport.AllAirlines
   * @generated
   */
  EClass getAllAirlines();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ecse439.project.airport.AllAirlines#getAirline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Airline</em>'.
   * @see org.xtext.ecse439.project.airport.AllAirlines#getAirline()
   * @see #getAllAirlines()
   * @generated
   */
  EReference getAllAirlines_Airline();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.AllFlights <em>All Flights</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>All Flights</em>'.
   * @see org.xtext.ecse439.project.airport.AllFlights
   * @generated
   */
  EClass getAllFlights();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ecse439.project.airport.AllFlights#getFlights <em>Flights</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Flights</em>'.
   * @see org.xtext.ecse439.project.airport.AllFlights#getFlights()
   * @see #getAllFlights()
   * @generated
   */
  EReference getAllFlights_Flights();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Schedule <em>Schedule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schedule</em>'.
   * @see org.xtext.ecse439.project.airport.Schedule
   * @generated
   */
  EClass getSchedule();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.Schedule#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Date</em>'.
   * @see org.xtext.ecse439.project.airport.Schedule#getDate()
   * @see #getSchedule()
   * @generated
   */
  EReference getSchedule_Date();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ecse439.project.airport.Schedule#getFlGate <em>Fl Gate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fl Gate</em>'.
   * @see org.xtext.ecse439.project.airport.Schedule#getFlGate()
   * @see #getSchedule()
   * @generated
   */
  EReference getSchedule_FlGate();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Flight <em>Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flight</em>'.
   * @see org.xtext.ecse439.project.airport.Flight
   * @generated
   */
  EClass getFlight();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Flight#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ecse439.project.airport.Flight#getName()
   * @see #getFlight()
   * @generated
   */
  EAttribute getFlight_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.Flight#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.ecse439.project.airport.Flight#getTime()
   * @see #getFlight()
   * @generated
   */
  EReference getFlight_Time();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Flight#getAirplaneSize <em>Airplane Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Airplane Size</em>'.
   * @see org.xtext.ecse439.project.airport.Flight#getAirplaneSize()
   * @see #getFlight()
   * @generated
   */
  EAttribute getFlight_AirplaneSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Flight#getReqRunwayLg <em>Req Runway Lg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Req Runway Lg</em>'.
   * @see org.xtext.ecse439.project.airport.Flight#getReqRunwayLg()
   * @see #getFlight()
   * @generated
   */
  EAttribute getFlight_ReqRunwayLg();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.FlGate <em>Fl Gate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fl Gate</em>'.
   * @see org.xtext.ecse439.project.airport.FlGate
   * @generated
   */
  EClass getFlGate();

  /**
   * Returns the meta object for the reference '{@link org.xtext.ecse439.project.airport.FlGate#getFlight <em>Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Flight</em>'.
   * @see org.xtext.ecse439.project.airport.FlGate#getFlight()
   * @see #getFlGate()
   * @generated
   */
  EReference getFlGate_Flight();

  /**
   * Returns the meta object for the reference '{@link org.xtext.ecse439.project.airport.FlGate#getGate <em>Gate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Gate</em>'.
   * @see org.xtext.ecse439.project.airport.FlGate#getGate()
   * @see #getFlGate()
   * @generated
   */
  EReference getFlGate_Gate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ecse439.project.airport.FlGate#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.ecse439.project.airport.FlGate#getTime()
   * @see #getFlGate()
   * @generated
   */
  EReference getFlGate_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Terminal <em>Terminal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Terminal</em>'.
   * @see org.xtext.ecse439.project.airport.Terminal
   * @generated
   */
  EClass getTerminal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Terminal#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ecse439.project.airport.Terminal#getName()
   * @see #getTerminal()
   * @generated
   */
  EAttribute getTerminal_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.ecse439.project.airport.Terminal#getRunway <em>Runway</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Runway</em>'.
   * @see org.xtext.ecse439.project.airport.Terminal#getRunway()
   * @see #getTerminal()
   * @generated
   */
  EReference getTerminal_Runway();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.ecse439.project.airport.Terminal#getGates <em>Gates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Gates</em>'.
   * @see org.xtext.ecse439.project.airport.Terminal#getGates()
   * @see #getTerminal()
   * @generated
   */
  EReference getTerminal_Gates();

  /**
   * Returns the meta object for the reference '{@link org.xtext.ecse439.project.airport.Terminal#getAirline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Airline</em>'.
   * @see org.xtext.ecse439.project.airport.Terminal#getAirline()
   * @see #getTerminal()
   * @generated
   */
  EReference getTerminal_Airline();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Runway <em>Runway</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Runway</em>'.
   * @see org.xtext.ecse439.project.airport.Runway
   * @generated
   */
  EClass getRunway();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Runway#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ecse439.project.airport.Runway#getName()
   * @see #getRunway()
   * @generated
   */
  EAttribute getRunway_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Runway#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.xtext.ecse439.project.airport.Runway#getLength()
   * @see #getRunway()
   * @generated
   */
  EAttribute getRunway_Length();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Runway#getUsed <em>Used</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Used</em>'.
   * @see org.xtext.ecse439.project.airport.Runway#getUsed()
   * @see #getRunway()
   * @generated
   */
  EAttribute getRunway_Used();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Gate <em>Gate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gate</em>'.
   * @see org.xtext.ecse439.project.airport.Gate
   * @generated
   */
  EClass getGate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Gate#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ecse439.project.airport.Gate#getName()
   * @see #getGate()
   * @generated
   */
  EAttribute getGate_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Gate#getMaxApSize <em>Max Ap Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Ap Size</em>'.
   * @see org.xtext.ecse439.project.airport.Gate#getMaxApSize()
   * @see #getGate()
   * @generated
   */
  EAttribute getGate_MaxApSize();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Airline <em>Airline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Airline</em>'.
   * @see org.xtext.ecse439.project.airport.Airline
   * @generated
   */
  EClass getAirline();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Airline#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ecse439.project.airport.Airline#getName()
   * @see #getAirline()
   * @generated
   */
  EAttribute getAirline_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Date <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Date</em>'.
   * @see org.xtext.ecse439.project.airport.Date
   * @generated
   */
  EClass getDate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Date#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see org.xtext.ecse439.project.airport.Date#getDay()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Day();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Date#getMonth <em>Month</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Month</em>'.
   * @see org.xtext.ecse439.project.airport.Date#getMonth()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Month();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Date#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.ecse439.project.airport.Date#getYear()
   * @see #getDate()
   * @generated
   */
  EAttribute getDate_Year();

  /**
   * Returns the meta object for class '{@link org.xtext.ecse439.project.airport.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.ecse439.project.airport.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Time#getHour <em>Hour</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hour</em>'.
   * @see org.xtext.ecse439.project.airport.Time#getHour()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Hour();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ecse439.project.airport.Time#getMinute <em>Minute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minute</em>'.
   * @see org.xtext.ecse439.project.airport.Time#getMinute()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Minute();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AirportFactory getAirportFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.DomainmodelImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getDomainmodel()
     * @generated
     */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ELEMENTS = eINSTANCE.getDomainmodel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.AirportImpl <em>Airport</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.AirportImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAirport()
     * @generated
     */
    EClass AIRPORT = eINSTANCE.getAirport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRPORT__NAME = eINSTANCE.getAirport_Name();

    /**
     * The meta object literal for the '<em><b>Schedule</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AIRPORT__SCHEDULE = eINSTANCE.getAirport_Schedule();

    /**
     * The meta object literal for the '<em><b>All Run</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AIRPORT__ALL_RUN = eINSTANCE.getAirport_AllRun();

    /**
     * The meta object literal for the '<em><b>All Gat</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AIRPORT__ALL_GAT = eINSTANCE.getAirport_AllGat();

    /**
     * The meta object literal for the '<em><b>All Air</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AIRPORT__ALL_AIR = eINSTANCE.getAirport_AllAir();

    /**
     * The meta object literal for the '<em><b>All Fli</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AIRPORT__ALL_FLI = eINSTANCE.getAirport_AllFli();

    /**
     * The meta object literal for the '<em><b>All Ter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AIRPORT__ALL_TER = eINSTANCE.getAirport_AllTer();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.AllTerminalsImpl <em>All Terminals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.AllTerminalsImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllTerminals()
     * @generated
     */
    EClass ALL_TERMINALS = eINSTANCE.getAllTerminals();

    /**
     * The meta object literal for the '<em><b>Terminals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALL_TERMINALS__TERMINALS = eINSTANCE.getAllTerminals_Terminals();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.AllRunwaysImpl <em>All Runways</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.AllRunwaysImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllRunways()
     * @generated
     */
    EClass ALL_RUNWAYS = eINSTANCE.getAllRunways();

    /**
     * The meta object literal for the '<em><b>Runways</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALL_RUNWAYS__RUNWAYS = eINSTANCE.getAllRunways_Runways();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.AllGatesImpl <em>All Gates</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.AllGatesImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllGates()
     * @generated
     */
    EClass ALL_GATES = eINSTANCE.getAllGates();

    /**
     * The meta object literal for the '<em><b>Gates</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALL_GATES__GATES = eINSTANCE.getAllGates_Gates();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.AllAirlinesImpl <em>All Airlines</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.AllAirlinesImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllAirlines()
     * @generated
     */
    EClass ALL_AIRLINES = eINSTANCE.getAllAirlines();

    /**
     * The meta object literal for the '<em><b>Airline</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALL_AIRLINES__AIRLINE = eINSTANCE.getAllAirlines_Airline();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.AllFlightsImpl <em>All Flights</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.AllFlightsImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAllFlights()
     * @generated
     */
    EClass ALL_FLIGHTS = eINSTANCE.getAllFlights();

    /**
     * The meta object literal for the '<em><b>Flights</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALL_FLIGHTS__FLIGHTS = eINSTANCE.getAllFlights_Flights();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.ScheduleImpl <em>Schedule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.ScheduleImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getSchedule()
     * @generated
     */
    EClass SCHEDULE = eINSTANCE.getSchedule();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULE__DATE = eINSTANCE.getSchedule_Date();

    /**
     * The meta object literal for the '<em><b>Fl Gate</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULE__FL_GATE = eINSTANCE.getSchedule_FlGate();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.FlightImpl <em>Flight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.FlightImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getFlight()
     * @generated
     */
    EClass FLIGHT = eINSTANCE.getFlight();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIGHT__NAME = eINSTANCE.getFlight_Name();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLIGHT__TIME = eINSTANCE.getFlight_Time();

    /**
     * The meta object literal for the '<em><b>Airplane Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIGHT__AIRPLANE_SIZE = eINSTANCE.getFlight_AirplaneSize();

    /**
     * The meta object literal for the '<em><b>Req Runway Lg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIGHT__REQ_RUNWAY_LG = eINSTANCE.getFlight_ReqRunwayLg();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.FlGateImpl <em>Fl Gate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.FlGateImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getFlGate()
     * @generated
     */
    EClass FL_GATE = eINSTANCE.getFlGate();

    /**
     * The meta object literal for the '<em><b>Flight</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FL_GATE__FLIGHT = eINSTANCE.getFlGate_Flight();

    /**
     * The meta object literal for the '<em><b>Gate</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FL_GATE__GATE = eINSTANCE.getFlGate_Gate();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FL_GATE__TIME = eINSTANCE.getFlGate_Time();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.TerminalImpl <em>Terminal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.TerminalImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getTerminal()
     * @generated
     */
    EClass TERMINAL = eINSTANCE.getTerminal();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERMINAL__NAME = eINSTANCE.getTerminal_Name();

    /**
     * The meta object literal for the '<em><b>Runway</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINAL__RUNWAY = eINSTANCE.getTerminal_Runway();

    /**
     * The meta object literal for the '<em><b>Gates</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINAL__GATES = eINSTANCE.getTerminal_Gates();

    /**
     * The meta object literal for the '<em><b>Airline</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINAL__AIRLINE = eINSTANCE.getTerminal_Airline();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.RunwayImpl <em>Runway</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.RunwayImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getRunway()
     * @generated
     */
    EClass RUNWAY = eINSTANCE.getRunway();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RUNWAY__NAME = eINSTANCE.getRunway_Name();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RUNWAY__LENGTH = eINSTANCE.getRunway_Length();

    /**
     * The meta object literal for the '<em><b>Used</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RUNWAY__USED = eINSTANCE.getRunway_Used();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.GateImpl <em>Gate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.GateImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getGate()
     * @generated
     */
    EClass GATE = eINSTANCE.getGate();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GATE__NAME = eINSTANCE.getGate_Name();

    /**
     * The meta object literal for the '<em><b>Max Ap Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GATE__MAX_AP_SIZE = eINSTANCE.getGate_MaxApSize();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.AirlineImpl <em>Airline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.AirlineImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getAirline()
     * @generated
     */
    EClass AIRLINE = eINSTANCE.getAirline();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AIRLINE__NAME = eINSTANCE.getAirline_Name();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.DateImpl <em>Date</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.DateImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getDate()
     * @generated
     */
    EClass DATE = eINSTANCE.getDate();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__DAY = eINSTANCE.getDate_Day();

    /**
     * The meta object literal for the '<em><b>Month</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__MONTH = eINSTANCE.getDate_Month();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE__YEAR = eINSTANCE.getDate_Year();

    /**
     * The meta object literal for the '{@link org.xtext.ecse439.project.airport.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ecse439.project.airport.impl.TimeImpl
     * @see org.xtext.ecse439.project.airport.impl.AirportPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Hour</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__HOUR = eINSTANCE.getTime_Hour();

    /**
     * The meta object literal for the '<em><b>Minute</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__MINUTE = eINSTANCE.getTime_Minute();

  }

} //AirportPackage
