/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Airlines</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ecse439.project.airport.AllAirlines#getAirline <em>Airline</em>}</li>
 * </ul>
 *
 * @see org.xtext.ecse439.project.airport.AirportPackage#getAllAirlines()
 * @model
 * @generated
 */
public interface AllAirlines extends EObject
{
  /**
   * Returns the value of the '<em><b>Airline</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ecse439.project.airport.Airline}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Airline</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airline</em>' containment reference list.
   * @see org.xtext.ecse439.project.airport.AirportPackage#getAllAirlines_Airline()
   * @model containment="true"
   * @generated
   */
  EList<Airline> getAirline();

} // AllAirlines
