/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fl Gate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ecse439.project.airport.FlGate#getFlight <em>Flight</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.FlGate#getGate <em>Gate</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.FlGate#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.ecse439.project.airport.AirportPackage#getFlGate()
 * @model
 * @generated
 */
public interface FlGate extends EObject
{
  /**
   * Returns the value of the '<em><b>Flight</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Flight</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flight</em>' reference.
   * @see #setFlight(Flight)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getFlGate_Flight()
   * @model
   * @generated
   */
  Flight getFlight();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.FlGate#getFlight <em>Flight</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flight</em>' reference.
   * @see #getFlight()
   * @generated
   */
  void setFlight(Flight value);

  /**
   * Returns the value of the '<em><b>Gate</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gate</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gate</em>' reference.
   * @see #setGate(Gate)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getFlGate_Gate()
   * @model
   * @generated
   */
  Gate getGate();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.FlGate#getGate <em>Gate</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gate</em>' reference.
   * @see #getGate()
   * @generated
   */
  void setGate(Gate value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(Time)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getFlGate_Time()
   * @model containment="true"
   * @generated
   */
  Time getTime();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.FlGate#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(Time value);

} // FlGate
