/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flight</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ecse439.project.airport.Flight#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.Flight#getTime <em>Time</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.Flight#getAirplaneSize <em>Airplane Size</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.Flight#getReqRunwayLg <em>Req Runway Lg</em>}</li>
 * </ul>
 *
 * @see org.xtext.ecse439.project.airport.AirportPackage#getFlight()
 * @model
 * @generated
 */
public interface Flight extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getFlight_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Flight#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(Time)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getFlight_Time()
   * @model containment="true"
   * @generated
   */
  Time getTime();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Flight#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(Time value);

  /**
   * Returns the value of the '<em><b>Airplane Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Airplane Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airplane Size</em>' attribute.
   * @see #setAirplaneSize(int)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getFlight_AirplaneSize()
   * @model
   * @generated
   */
  int getAirplaneSize();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Flight#getAirplaneSize <em>Airplane Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Airplane Size</em>' attribute.
   * @see #getAirplaneSize()
   * @generated
   */
  void setAirplaneSize(int value);

  /**
   * Returns the value of the '<em><b>Req Runway Lg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Req Runway Lg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req Runway Lg</em>' attribute.
   * @see #setReqRunwayLg(int)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getFlight_ReqRunwayLg()
   * @model
   * @generated
   */
  int getReqRunwayLg();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Flight#getReqRunwayLg <em>Req Runway Lg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Req Runway Lg</em>' attribute.
   * @see #getReqRunwayLg()
   * @generated
   */
  void setReqRunwayLg(int value);

} // Flight
