/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ecse439.project.airport.Terminal#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.Terminal#getRunway <em>Runway</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.Terminal#getGates <em>Gates</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.Terminal#getAirline <em>Airline</em>}</li>
 * </ul>
 *
 * @see org.xtext.ecse439.project.airport.AirportPackage#getTerminal()
 * @model
 * @generated
 */
public interface Terminal extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getTerminal_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Terminal#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Runway</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Runway</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runway</em>' reference.
   * @see #setRunway(Runway)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getTerminal_Runway()
   * @model
   * @generated
   */
  Runway getRunway();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Terminal#getRunway <em>Runway</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Runway</em>' reference.
   * @see #getRunway()
   * @generated
   */
  void setRunway(Runway value);

  /**
   * Returns the value of the '<em><b>Gates</b></em>' reference list.
   * The list contents are of type {@link org.xtext.ecse439.project.airport.Gate}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gates</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gates</em>' reference list.
   * @see org.xtext.ecse439.project.airport.AirportPackage#getTerminal_Gates()
   * @model
   * @generated
   */
  EList<Gate> getGates();

  /**
   * Returns the value of the '<em><b>Airline</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Airline</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Airline</em>' reference.
   * @see #setAirline(Airline)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getTerminal_Airline()
   * @model
   * @generated
   */
  Airline getAirline();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Terminal#getAirline <em>Airline</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Airline</em>' reference.
   * @see #getAirline()
   * @generated
   */
  void setAirline(Airline value);

} // Terminal
