/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ecse439.project.airport.Time#getHour <em>Hour</em>}</li>
 *   <li>{@link org.xtext.ecse439.project.airport.Time#getMinute <em>Minute</em>}</li>
 * </ul>
 *
 * @see org.xtext.ecse439.project.airport.AirportPackage#getTime()
 * @model
 * @generated
 */
public interface Time extends EObject
{
  /**
   * Returns the value of the '<em><b>Hour</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hour</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hour</em>' attribute.
   * @see #setHour(int)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getTime_Hour()
   * @model
   * @generated
   */
  int getHour();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Time#getHour <em>Hour</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hour</em>' attribute.
   * @see #getHour()
   * @generated
   */
  void setHour(int value);

  /**
   * Returns the value of the '<em><b>Minute</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Minute</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minute</em>' attribute.
   * @see #setMinute(int)
   * @see org.xtext.ecse439.project.airport.AirportPackage#getTime_Minute()
   * @model
   * @generated
   */
  int getMinute();

  /**
   * Sets the value of the '{@link org.xtext.ecse439.project.airport.Time#getMinute <em>Minute</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minute</em>' attribute.
   * @see #getMinute()
   * @generated
   */
  void setMinute(int value);

} // Time
