/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAirportScopeProvider extends DelegatingScopeProvider {
}
