/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.ecse439.project.airport.ui.internal.AirportActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AirportExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AirportActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AirportActivator.getInstance().getInjector(AirportActivator.ORG_XTEXT_ECSE439_PROJECT_AIRPORT);
	}
	
}
