/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.ecse439.project.ui.AbstractAirportUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AirportUiModule extends AbstractAirportUiModule {
  public AirportUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
