/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.ecse439.project.airport.ui.internal.AirportActivator;

public class AirportUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AirportActivator.getInstance().getInjector("org.xtext.ecse439.project.Airport");
	}

}
