/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.ecse439.project.airport.AirportPackage;
import org.xtext.ecse439.project.airport.AllRunways;
import org.xtext.ecse439.project.airport.Runway;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>All Runways</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ecse439.project.airport.impl.AllRunwaysImpl#getRunways <em>Runways</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AllRunwaysImpl extends MinimalEObjectImpl.Container implements AllRunways
{
  /**
   * The cached value of the '{@link #getRunways() <em>Runways</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRunways()
   * @generated
   * @ordered
   */
  protected EList<Runway> runways;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AllRunwaysImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AirportPackage.Literals.ALL_RUNWAYS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Runway> getRunways()
  {
    if (runways == null)
    {
      runways = new EObjectContainmentEList<Runway>(Runway.class, this, AirportPackage.ALL_RUNWAYS__RUNWAYS);
    }
    return runways;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_RUNWAYS__RUNWAYS:
        return ((InternalEList<?>)getRunways()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_RUNWAYS__RUNWAYS:
        return getRunways();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_RUNWAYS__RUNWAYS:
        getRunways().clear();
        getRunways().addAll((Collection<? extends Runway>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_RUNWAYS__RUNWAYS:
        getRunways().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_RUNWAYS__RUNWAYS:
        return runways != null && !runways.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AllRunwaysImpl
