/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.airport.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.ecse439.project.airport.AirportPackage;
import org.xtext.ecse439.project.airport.AllTerminals;
import org.xtext.ecse439.project.airport.Terminal;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>All Terminals</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ecse439.project.airport.impl.AllTerminalsImpl#getTerminals <em>Terminals</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AllTerminalsImpl extends MinimalEObjectImpl.Container implements AllTerminals
{
  /**
   * The cached value of the '{@link #getTerminals() <em>Terminals</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerminals()
   * @generated
   * @ordered
   */
  protected EList<Terminal> terminals;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AllTerminalsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AirportPackage.Literals.ALL_TERMINALS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Terminal> getTerminals()
  {
    if (terminals == null)
    {
      terminals = new EObjectContainmentEList<Terminal>(Terminal.class, this, AirportPackage.ALL_TERMINALS__TERMINALS);
    }
    return terminals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_TERMINALS__TERMINALS:
        return ((InternalEList<?>)getTerminals()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_TERMINALS__TERMINALS:
        return getTerminals();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_TERMINALS__TERMINALS:
        getTerminals().clear();
        getTerminals().addAll((Collection<? extends Terminal>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_TERMINALS__TERMINALS:
        getTerminals().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AirportPackage.ALL_TERMINALS__TERMINALS:
        return terminals != null && !terminals.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AllTerminalsImpl
