/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ecse439.project.parser.antlr.internal.InternalAirportParser;
import org.xtext.ecse439.project.services.AirportGrammarAccess;

public class AirportParser extends AbstractAntlrParser {

	@Inject
	private AirportGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAirportParser createParser(XtextTokenStream stream) {
		return new InternalAirportParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public AirportGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AirportGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
