/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.validation;

import org.xtext.ecse439.project.validation.AbstractAirportValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AirportValidator extends AbstractAirportValidator {
}
