/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ecse439.project.validation

import org.eclipse.xtext.validation.Check
import org.xtext.ecse439.project.airport.AirportPackage
import org.xtext.ecse439.project.airport.FlGate
import org.xtext.ecse439.project.airport.Flight
import org.xtext.ecse439.project.airport.Gate
import org.xtext.ecse439.project.airport.Runway

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class AirportValidator extends AbstractAirportValidator {	
	
}
